model:
  audio:
    alm_model: "whisper-large-v2"
    sample_rate: 16000
    chunk_size: 512
    feature_dim: 768
  
  video:
    frame_rate: 30
    frame_size: [224, 224]
    feature_dim: 512
    
  fusion:
    hidden_dim: 768
    num_heads: 8
    num_layers: 4
    dropout: 0.1

training:
  batch_size: 32
  learning_rate: 0.0001
  num_epochs: 50
  device: "cuda"
  
pipeline:
  buffer_size: 1000
  threshold: 0.7