datasets:
  avspeech:
    path: /path/to/avspeech
    weight: 0.4
  havic:
    path: /path/to/havic
    weight: 0.4
  gaze:
    path: /path/to/gazecapture
    weight: 0.2

training:
  pretrain:
    epochs: 50
    batch_size: 32
    learning_rate: 0.0001
    scheduler:
      type: "cosine"
      warmup_steps: 1000
  
  finetune:
    epochs: 20
    batch_size: 16
    learning_rate: 0.00001
    scheduler:
      type: "linear"
      warmup_steps: 100

model:
  audio:
    alm_model: "whisper-large-v2"
    feature_dim: 768
  
  video:
    frame_size: [224, 224]
    feature_dim: 512
    
  fusion:
    hidden_dim: 768
    num_heads: 8
    num_layers: 4
    dropout: 0.1

augmentation:
  audio:
    noise_injection: true
    speed_perturbation: true
    pitch_shift: true
  
  video:
    random_crop: true
    color_jitter: true
    random_flip: true
    rotation: [-15, 15]