dataset:
  root_dir: "video_model\src\data\dataset\GRID\video"
  train_subjects: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25]
  val_subjects: [26, 27, 28, 29]
  test_subjects: [30, 31, 32, 33]
  sequence_length: 16
  stride: 8

model:
  face_size: [112, 112]
  num_classes: 2

training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 10
  device: "cuda"